version: 2.1
commands: # a reusable command with parameters
   greeting:
      parameters:
         to:
           default: "world"
           type: string
      steps:
         - run: echo "Hello <<parameters.to>>"
jobs:
   my-first-job:
      docker:
         - image: circleci/openjdk:8u171-jdk
      steps:
         - greeting:
            to: "Rishi Khurana"
   my-second-job:
      docker:
         - image: circleci/openjdk:8u171-jdk
      steps:
         - greeting:
            to: "Elon"
workflows:
   my-workflow:
      jobs:
         - my-first-job
         - my-second-job         